apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: todos
  REPLICATION_USER: replicationuser
  REPLICATION_PASSWORD: replicationPassword